
server:
  port: 9001

spring:
  application:
    name: spring-db
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_study
    username: root
    password: mariadb
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          format_sql: true
          database: mysql


# Mybatis Setting
mybatis:
  # SQL 파일의 위치  classpath - resources 파일 내에서 찾기, file - 로컬에서 찾기
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.spring.database.chap03

logging:
  level:
    root: INFO
    com.spring.database: DEBUG
    org:
      hibernate:
        SQL: DEBUG


